### PR TITLE
arm64: dts: Add L2 cache topology to Hi6220

### PR DESCRIPTION
**Pull request by Leo-Yan**
Enable L2 cache topology for Hi6220.

### CODE REVIEW

**Comment by docularxu** [comment]
Leo, will you submit this patch to upstream?

**Comment by docularxu** [comment]
I will add this commit to my next update of hikey-tracking-dts branch.

**Comment by Leo-Yan** [comment]
On Wed, Mar 02, 2016 at 05:02:24AM -0800, Guodong Xu wrote:

> Leo, will you submit this patch to upstream?

Yes. This patch has been sent out and suppose Wei Xu will merge into
his branch for mainline merging.

**Comment by docularxu** [comment]
Merged.

**Pull request closed without merging**
