### PR TITLE
Support for OP-TEE generic linux driver

### PR DESCRIPTION
**Pull request by vchong**
Hi @docularxu,

As discussed with @fboudra last night, here are the patches required to support OP-TEE's new generic linux driver. Please review.

Thanks!

### CODE REVIEW

**Comment by vchong** [comment]
This PR is based on following topic branch: https://github.com/linaro-swg/linux/commits/optee

**Comment by vchong** [comment]
Add @jenswi-linaro @jbech-linaro @rsalveti 
fyi..

**Comment by docularxu** [comment]
In HiKey project, I don't want to include modifications to other dt.

d8813b6 arm64: dt: Add OP-TEE firmware to mt8173 **not for mainline**
979842a arm64: dt: OP-TEE for Juno **not for mainline**
9416756 arm64: dt: OP-TEE for qemu-v8 **not for mainline**
037ccd1 arm64: dt: OP-TEE for foundation-v8 **not for mainline**
4b06c8f arm64: dt: use GICv2 for foundation-v8 **not for mainline**
83eb922 arm64: dt: PSCI for foundation-v8 **not for mainline**

Victor, and @jenswi-linaro @jbech-linaro @rsalveti
Would you submit these dt changes to RP (Amit K is maintainer) directly?

-Guodong

**Comment by vchong** [comment]
@docularxu That's fine. I have them here for consistency sake with the https://github.com/linaro-swg/linux/commits/optee reference branch, but if you don't want those, do you want me to remove them, or you will remove them yourself?

These changes are already merged by @idlethread (Amit) to RPK (https://github.com/96boards/linux/commits/96b/releases/2016.06) on April 21st.

Thanks!

**Comment by idlethread** [comment]
Since SWG doesn't want to maintain an OP-TEE branch on a vanilla 4.4 and I
don't really want all the LSK changes into RPK, I'm maintaining OP-TEE on
vanilla 4.4 at https://github.com/96boards/linux/tree/projects/op-tee. This
branch has been merged into 96b/releases/16.06 for the next RPB release.

**Comment by vchong** [comment]
Closing this PR as it's not required anymore due to this repo now having its own op-tee tracking branch @ https://github.com/96boards-hikey/linux/commits/hikey-tracking-optee.

**Pull request closed without merging**
