### PR TITLE
update arm gpu to r9p0

### PR DESCRIPTION
**Pull request by photoszzt**

### CODE REVIEW

**Comment by photoszzt** [comment]
I notice that there's a pull request for the same purpose but it doesn't have much followup. I did a comparison between my patch and the android-hikey960-4.14 patch. Most of them are similar but there's one patch in android that looks strange. 

In drivers/gpu/arm_gpu/ipa/mali_kbase_ipa.c line 112, android version adds this line:

of_node_get(model->kbdev->dev->of_node);

which doesn't belong to the arm released driver.  I wonder if there's any reference counting issue in the original driver. 

Tallguy-74's patch also deletes a bunch files that are not needed but the Android version keeps them. For example the mali_kbase_mmu_mode.h.

**Comment by photoszzt** [comment]
My output of clinfo is here: https://pastebin.com/S7HUc4h1

**Comment by docularxu** [comment]
@photoszzt hi,

Branch :hikey960-upstream-rebase is not maintained for a while. Sorry. John (@johnstultz-work) maintains a working branch for 4.14 here [1], please have a look if you are interested.

[1] https://git.linaro.org/people/john.stultz/android-dev.git/refs/heads

-Guodong

**Comment by photoszzt** [comment]
@docularxu @johnstultz-work  Can I use that branch for open embedded? If so, which branch should I use?

**Comment by photoszzt** [comment]
Should I use dev/hikey960-4.14 branch?

**Comment by johnstultz-work** [comment]
If you want to use 4.14, I'd recommend the android-hikey-linaro-4.14 branch from:
https://android.googlesource.com/kernel/hikey-linaro 

If you need a mainline based branch I maintain one (fair warning the tree is constantly rebased w/ mainline):  https://git.linaro.org/people/john.stultz/android-dev.git  dev/hikey960-mainline-WIP

These are both only tested w/ the current AOSP/master branch, but assuming you can get working mali binaries (currently r9p0) then it should be usable w/ other linux environments (potentially requiring some kernel config changes).

**Comment by photoszzt** [comment]
@johnstultz-work  @docularxu  For configs, I know hikey960_defconfig is only for android. I also find a defconfig file in configs. Is that one good for general linux? I heard people try hikey960_defconfig for open embedded and that won't work. Linaro also release a dev build for open embedded. Do you have a pointer to the config file used for that linux?

**Comment by johnstultz-work** [comment]
You can try defconfig, but I'm not sure if it will work. I'd start w/ the hikey960_defconfig and make changes from there to enable other linux distros.  Unfortunately I'm focused on AOSP, so I'm not much help with other environments.

**Comment by photoszzt** [comment]
I see. Thanks!

**Comment by photoszzt** [comment]
Well, I will stick with this branch for now. I install the hikey960_defconfig build and the board hangs in boot.

**Comment by photoszzt** [comment]
I can use the defconfig from the upstream branch in the android tree. The build works.

**Comment by photoszzt** [comment]
Though it's closed, the build on android kernel needs more adjustment to be usable. git, wget and ifconfig can't connect to network in the user permission.

**Comment by TallGuy74** [comment]
This is caused by CONFIG_ANDROID_PARANOID_NETWORK being enabled.
Disable this and that should go away.

**Comment by photoszzt** [comment]
@TallGuy74  yeah, I find that when I'm searching android keywords in my config.

**Pull request closed without merging**
